### ISSUE TITLE
sample.js fails to run with SpiderMonkey

### ISSUE THREAD

**Issue by typewriter7051** [ge9/kage-engine-2#1]
Running ``js sample.js > output.svg`` fails with SpiderMonkey (tested versions 78, 91, 115, 128) and gives the following error.

```
/kage-engine-2/2d.js:51:1 SyntaxError: export declarations may only appear at top level of a module:
/kage-engine-2/2d.js:51:1 export function isCrossBoxWithOthers(strokesArray, i, bx1, b
/kage-engine-2/2d.js:51:1 ^
Stack:
  @sample.js:6:5
```

After messing around a bit, it seems that all exported functions cause it to fail.

**Comment by typewriter7051** [comment]
Changing the ``load("foo.js");`` to an import then running as module ``-m`` fixes the issue. Here is part of the new ``sample.js``:

```js
// KAGE engine sample script for JavaScript engine
//
// % js -m sample.js > result.svg (SpiderMonkey)
// % java -jar js.jar sample.js > result.svg (Rhino untested)

import { Kage } from "kage.js";
import { Polygons } from "polygons.js";

var kage = new Kage();
var polygons = new Polygons();
```

**Comment by ge9** [comment]
Ah, sorry, this repository is meant to have as least change from the original KAGE engine as possible and so may not work correctly as JavaScript module.  I updated the description. Thank you for reporting.
